In [2]:
import numpy as np
from scipy import stats

### 1. Crear un vector con valores dentro del rango 10 a 49.

In [3]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 2. Invertir el vector creado en el ejercicio 1.

In [4]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 3. Crear una matriz de 3x3 con los valores de 0 a 8.

In [105]:
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Encontrar los índices que no son ceros del arreglo  [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0].

In [7]:
arr = np.array([1, 2, 4, 2, 4, 0, 1, 0, 0, 0, 12, 4, 5, 6, 7, 0])
arr.nonzero()

(array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14], dtype=int64),)

### 5. Crear una matriz identidad de 6x6.

In [8]:
np.eye(6, dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### 6. Encontrar los índices de los valores mínimos y máximos de la matriz creada en el ejercicio 3.

In [106]:
print('Min values indexes:', *zip(*np.where(matrix_3x3 == matrix_3x3.min())))
print('Max values indexes:', *zip(*np.where(matrix_3x3 == matrix_3x3.max())))

Min values indexes: (0, 0)
Max values indexes: (2, 2)


### 7. Crear una matriz de 10x10 con 1 en los bordes y 0 en el interior (con rangos de índices).

In [9]:
size, border_size = 10, 1
matrix_10x10 = np.ones((size, size), dtype='int')
matrix_10x10[border_size:size - border_size, border_size:size - border_size] = 0
matrix_10x10

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 8. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4.

In [16]:
times = 5
np.vstack([list(range(times)) for i in range(times)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 9. Crear dos arreglos al azar A y B, verificar si son iguales.

In [45]:
rand_min, rand_max = 0, 5
shape = 3, 2
arr_rand1 = np.random.randint(rand_min, rand_max, shape)
arr_rand2 = np.random.randint(rand_min, rand_max, shape)
print(f"""
{arr_rand1}

{arr_rand2}

Equals: {np.array_equal(arr_rand1, arr_rand2)}
""")



[[0 0]
 [1 0]
 [0 0]]

[[2 4]
 [4 3]
 [2 2]]

Equals: False



### 10.Crear una matriz de 20x20 de valores aleatorios entre 1 y 100, luego indicar su media, su mediana, su moda y el desvío estándar. Los valores que den como resultado flotantes deben tener como máximo 2 decimales.

In [123]:
rand_min, rand_max = 1, 101
shape = 20, 20
matrix_20x20 = np.random.randint(rand_min, rand_max, shape)
print(
f"""{matrix_20x20}

Mean: {np.mean(matrix_20x20):.2f}
Median: {np.median(matrix_20x20):.2f}
Mode: {stats.mode(matrix_20x20, axis=None)[0][0]}
Standard deviation: {np.std(matrix_20x20):.2f}
"""
)

[[ 38   4  78  69  24  95  45  10  90  44  46  47  63  23  87  95  15  90
   98  89]
 [ 77  15  80  31  37  57  35  85  14  29  52  27  78  68  37  91  18  75
   35   6]
 [ 36  53  39  39   8  86  45  48  34  68  58   8  73  44 100  63  71  23
   75  13]
 [ 24  55  45  59  83  49  41  62  81  64  22  63  19  48  70  79  64  43
   38  39]
 [  9  55  23  58   8  42  15  70  70  54  11  83  67  75  23  14   8  46
   15  55]
 [ 98  31   2  56   2  16  87  27   9  42  98  90  31  67  78   7  38  28
   37  56]
 [ 89  26  60   8   6  41  17  95  27  76  33  11  97   5  12  30  75  29
   68  51]
 [ 48  66  37  37  20  80  19   5  73  24   6  33  10  94  90  33  18  61
   38  48]
 [ 12  29   8  88  21   2  82   5  80  21  83   5  22  81  18  27  44  38
   92   3]
 [  4  53  53  85  43  58 100  83 100  23  21  51  91  56  64  49  82  56
   25  33]
 [ 21   1  59   1   3  95  66  42  20  41  20  34  85  60  85  69  50  71
   43  91]
 [ 94  72  51  83  12  82  71  27  62  36  78  11  34  22  21  10

### 11.Crear dos arreglos de 4 elementos enteros y hacer las siguientes operaciones: sumarlos, restarle el segundo al primero, multiplicarlos, dividir el primero por el segundo. Hacerlo utilizando métodos.

In [12]:
arr1 = np.array([1, 2, 3, 4]) 
arr2 = np.array([5, 6, 7, 8])
print(f"""
Sum: {np.add(arr1, arr2)}
Diff: {np.subtract(arr1, arr2)}
Mult: {np.multiply(arr1, arr2)}
Div: {np.divide(arr1, arr2)}
""")



Sum: [ 6  8 10 12]
Diff: [-4 -4 -4 -4]
Mult: [ 5 12 21 32]
Div: [0.2        0.33333333 0.42857143 0.5       ]



### 12.Crear una matriz de 4x4 de valores aleatorios entre 1 y 10, y luego agregarle una fila de 0s al final.

In [13]:
rand_min, rand_max = 1, 11
shape = 4, 4
matrix_4x4 = np.random.randint(rand_min, rand_max, shape)

np.append(matrix_4x4, [np.zeros(shape[0], dtype='int')], axis=0)

array([[ 3,  7,  6,  9],
       [ 3,  2,  6,  2],
       [ 9, 10,  3,  5],
       [ 7,  1, 10,  8],
       [ 0,  0,  0,  0]])

### 13.Crear dos arreglos de 6 elementos de valores aleatorios entre 0 y 1 y luego realizar las operaciones lógicas and y or con los métodos de NumPy.

In [129]:
rand_min, rand_max = 0, 2
qty = 6
arr1 = np.random.randint(rand_min, rand_max, qty)
arr2 = np.random.randint(rand_min, rand_max, qty)

print(
f"""
a. {arr1}

b. {arr2}

AND: {np.logical_and(arr1, arr2)}

OR: {np.logical_or(arr1 ,arr2)}
""")


a. [0 1 1 1 0 1]

b. [0 0 1 0 0 1]

AND: [False False  True False False  True]

OR: [False  True  True  True False  True]



### 14.Crear un arreglo de 4 elementos de entre 0 y 10, informar la cantidad de elementos que tiene y también cuántos bytes ocupa el arreglo.

In [130]:
rand_min, rand_max = 0 , 11
size = 4
arr = np.random.randint(rand_min, rand_max, size)
print(arr)
print(f'Elements: {arr.size}, Total bytes: {arr.itemsize * arr.size}')

[3 2 1 3]
Elements: 4, Total bytes: 16


### 15.Crear una matriz que contenga información en distintos formatos, imprimir la info de cada formato a través del atributo.

In [128]:
data = np.rec.array([('Jose', 32, 4321.2), ('Laura', 54, 5644.2), ('Juana', 31, 3453)], 
                    dtype=[('name', 'U10'), ('age', 'i'), ('income', 'f8')])

print(f"""Name: {data.name.dtype}
Age: {data.age.dtype}
Income: {data.income.dtype}""")

Name: <U10
Age: int32
Income: float64
